### ISSUE TITLE
Explainer for Govpress terminology

### ISSUE THREAD

**Issue by gazaston** [dxw/brandbook#24]
As laid out by Meyric — https://trello.com/c/3EvhAOrV/38-govpress#comment-5a74a46154dc9bcf4bb2c38d

**Comment by mec** [comment]
I'm wondering if this is not opened out to a wider section 'Talking about our brand' to take in how everything fits together?

**Comment by gazaston** [comment]
We have this section – https://dxw.github.io/brandbook/#/?id=we-are-dxw – which it might fit well in?

**Comment by mec** [comment]
Yeah, that is where I've put it as a first stab.

#25

**Comment by gazaston** [comment]
Merged #25 — closing this issue.
